name: Build and Publish .NET Project

on:
  push:
    tags:
      - 'v*'

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: 'cs2-web-login'
  V_PLACE_HOLDER: {{ github.ref_name }}

permissions:
  packages: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Envsubst
      run: |
          envsubst "\$V_PLACE_HOLDER" < cs2-web-login/Main.cs > cs2-web-login/Main.cs.tmp
          mv cs2-web-login/Main.cs.tmp cs2-web-login/Main.cs

    - name: Restore dependencies
      run: dotnet restore 
    
    - name: Build
      run: dotnet build --configuration Release --no-restore -p GIT_TAG=${{ github.ref_name }}
    
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ${{ env.PROJECT_NAME }}
    
    - name: Compress files
      run: |
        cd ${{ env.PROJECT_NAME }}
        rm -rf Microsoft* runtimes Serilog* Scrutor* System* McMaster*
        cd ..
        zip -r release-${{ github.ref_name }}.zip ${{ env.PROJECT_NAME }}
    
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: Release ${{ github.ref_name }}
        files: release-${{ github.ref_name }}.zip
        prerelease: false
