name: Build and Publish .NET Project

on:
  push:
    tags:
      - '*'

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: 'cs2-web-login'
  PUBLISH_DIR: 'publish'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}
    
    - name: Build
      run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_NAME }} --configuration Release --no-build --output ${{ env.PUBLISH_DIR }}
    
    - name: Compress files
      run: |
        cd ${{ env.PUBLISH_DIR }}
        rm -rf Microsoft* runtimes Serilog* Scrutor* System* McMaster*
        zip -r ../release.zip *
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release.zip

